/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f1xx.h"
#include "uart.h"
#include "i2c.h"
#include "aht20.h"
#include <stdio.h>

// Variáveis globais
float temperature;
float humidity;

int main(void) {
    UART_Init();                 // Inicializa UART
    delay_init();                // Inicializa delay
    print_uart("Inicializando sistema...\r\n");

    AHT20_Init();                // Inicializa I2C e sensor
    delay_ms(100);               // Aguarda estabilização

    while (1) {
        AHT20_ReadTemperatureHumidity(&temperature, &humidity);

        // Converte os valores float para parte inteira e decimal (duas casas)
        int ti = (int)temperature;
        int tf = (int)((temperature - ti) * 100);

        int hi = (int)humidity;
        int hf = (int)((humidity - hi) * 100);

        // Envia pela UART
        char buf[64];
        sprintf(buf, "Temp: %d.%02d C | Umid: %d.%02d %%\r\n", ti, tf, hi, hf);
        uart_write((uint8_t*)buf);

        delay_ms(10); // Aguarda 1 segundo
    }
}
